version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    allow:
      - dependency-type: production
    schedule:
      interval: daily
      time: "06:00"
      timezone: America/Los_Angeles
    assignees:
      - catchen
    reviewers:
      - catchen
    labels:
      - accept2ship

  - package-ecosystem: npm
    directory: "/"
    allow:
      - dependency-type: development
    schedule:
      interval: daily
      time: "06:00"
      timezone: America/Los_Angeles
    assignees:
      - catchen
    labels:
      - pass2ship

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: America/Los_Angeles
    assignees:
      - catchen
    labels:
      - pass2ship
