name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, '[0-9]+-[0-9]+-*']
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          check-latest: true

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint --fix

      - name: Build
        run: yarn build

      - name: Package
        run: yarn package

      - uses: CatChen/check-git-status-action@v1
        id: check-git-status
        with:
          fail-if-not-clean: ${{ github.actor != 'dependabot[bot]' || github.actor_id != 49699333 }}
          push-if-not-clean: true
          request-changes-if-not-clean: false
          push-token: ${{ secrets.CHECK_GIT_STATUS_ACTION_TOKEN }}
          request-changes-token: ${{ secrets.GITHUB_TOKEN }}
