name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "[0-9]+-[0-9]+-*"]
  workflow_run:
    workflows: ["Build for Dependabot"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    name: Build
    if: |-
      ${{
        (github.event_name == 'push' && github.actor != 'dependabot[bot]') ||
        (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]') ||
        (github.event_name == 'workflow_run' && github.actor == 'dependabot[bot]')
      }}
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event_name != 'workflow_run' }}

      - uses: actions/checkout@v3
        if: ${{ github.event_name == 'workflow_run' }}
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Start check run
        id: start-check-run
        if: ${{ github.event_name == 'workflow_run' }}
        run: |
          RUN_ID=$(gh api \
            -H "Accept: application/vnd.github+json" \
            "/repos/$GITHUB_ACTION_REPOSITORY/check-runs" \
            -f name="Build" \
            -f head="$GITHUB_SHA" \
            -f status="in_progress" \
            -q .id)
          echo "::set-output name=run-id::$RUN_ID"

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          check-latest: true

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Package
        run: yarn package

      - uses: CatChen/check-git-status-action@v1
        id: check-git-status
        with:
          fail-if-not-clean: ${{ github.actor != 'dependabot[bot]' }}
          push-if-not-clean: true
          github-token: ${{ secrets.CHECK_GIT_STATUS_ACTION_TOKEN }}

      - name: End check run
        if: ${{ always() && steps.check-git-status.outputs.run-id != '' }}
        env:
          RUN_ID: ${{ steps.check-git-status.outputs.run-id }}
          CONCLUSION: ${{ github.event.workflow_run.conclusion }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            "/repos/$GITHUB_ACTION_REPOSITORY/check-runs/$RUN_ID" \
            -f status="completed" \
            -f conclusion="$CONCLUSION"
